/* Project Euler
 * - JustCoderdev solution to 012 - 2024.03.03
 *
 *
 * Highly Divisible Triangular Number
 *	The sequence of triangle numbers is generated by adding
 *	the natural numbers. So the 7th triangle number would be
 *	1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 *		1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 *  Let us list the factors of the first seven triangle numbers:
 *  	 1: 1
 *  	 3: 1, 3
 *  	 6: 1, 2, 3, 6
 *  	10: 1, 2, 5, 10
 *  	15: 1, 3, 5, 15
 *  	21: 1, 3, 7, 21
 *  	28: 1, 2, 4, 7, 14, 28
 *
 *  We can see that 28 is the first triangle number to have over five divisors.
 *
 *  What is the value of the first triangle number to have over five hundred
 *  divisors?
 *
 *  Mac:
 *  Optimized O3 time: 10:58.15
 */

#include <stdio.h>
/* #include <stdlib.h> */

#include "lib/jctypes.h"
#include "lib/logger.h"
/* #include "lib/sgr.h" */

n64 triangle_number_get(n64 n)
{
	/* n != 0 */

	/* 5 (3) */
	/* 1 + 2 + 3 + 4 + 5 = 15 */
	/*         5 + 5 + 5 = 15 */

	/* 4 (2+1/2) */
	/* 1 + 2 + 3 + 4 = 10 */
	/*     2 + 4 + 4 = 10 */

	n64 number = n;

	if(n % 2 == 0)
	{
		number *= (n / 2);
		number += (n / 2);
	}
	else
	{
		number *= (n / 2) + 1;
	}

	return number;
}

n64 number_factors_get(n64 n)
{
	/* n != 1 */
	/* n: 1, ..., n*/
	n64 factors, first_factor, i;
	factors = first_factor = 1;

	/* printf("%lu: 1, ", n); */
	for(i = 2; i < n; ++i)
	{
		if(n % i == 0)
		{
			/* printf("%lu, ", i); */
			first_factor = i;
			factors++;
			break;
		}
	}

	for(i = first_factor + 1; i <= (n / first_factor); ++i)
	{
		if(n % i == 0)
		{
			/* printf("%lu, ", i); */
			factors++;
		}
	}

	/* if(n > 3) */
	/* { */
	/*  printf("%lu ", n); */
	factors++;
	/* } */

	/* printf("\n"); */
	return factors;
}

int main(void)
{
	/* #define NUMBERS_LEN 10 */
	/* n64 numbers[NUMBERS_LEN], i; */
	/* n64 CORRECT_NUMBERS[NUMBERS_LEN] =
	 * {1, 3, 6, 10, 15, 21, 28, 36, 45, 55}; */

	n64 triangle_number, divisors = 0;
	n64 i;

	for(i = 1; divisors < 500; ++i)
	{
		triangle_number = triangle_number_get(i);
		divisors = number_factors_get(triangle_number);
		/* printf(" (%lu)\n", divisors); */
	}

	printf("The triangle number %lu has %lu divisors\n",
		   triangle_number,
		   divisors);

	/* for(i = 0; i < NUMBERS_LEN; ++i) */
	/* { */
	/* 	numbers[i] = triangle_number(i + 1); */
	/* 	printf("%lu: %lu\t", i + 1, numbers[i]); */
	/* } */

	/* for(i = 0; i < NUMBERS_LEN; ++i) */
	/* 	log_assert(numbers[i] == CORRECT_NUMBERS[i]); */

	return 0;
}
